In [1]:
import pandas as pd

In [2]:
cleanedData = pd.read_csv("student_productivity_distraction_dataset_20000.csv")

In [3]:
cleanedData.head()

,student_id,age,gender,study_hours_per_day,sleep_hours,phone_usage_hours,social_media_hours,youtube_hours,gaming_hours,breaks_per_day,coffee_intake_mg,exercise_minutes,assignments_completed,attendance_percentage,stress_level,focus_score,final_grade,productivity_score
0,1,23,Female,4.35,3.63,3.38,2.73,1.83,5.26,6,347,111,2,57.21,10,57,81.87,33.78
1,2,20,Male,6.14,6.58,5.48,1.51,3.13,1.73,13,403,28,10,91.27,10,49,60.90,48.99
2,3,29,Female,4.98,3.26,4.83,3.63,0.18,4.71,1,419,102,8,63.14,2,38,86.22,36.60
3,4,27,Female,3.19,4.58,10.06,3.95,5.75,2.52,9,178,28,18,40.51,6,50,71.77,19.87
4,5,24,Male,7.67,6.21,3.02,1.59,5.46,5.65,8,436,105,7,45.53,6,41,90.13,52.90

In [4]:
cleanedData.columns

Index(['student_id', 'age', 'gender', 'study_hours_per_day', 'sleep_hours',
       'phone_usage_hours', 'social_media_hours', 'youtube_hours',
       'gaming_hours', 'breaks_per_day', 'coffee_intake_mg',
       'exercise_minutes', 'assignments_completed', 'attendance_percentage',
       'stress_level', 'focus_score', 'final_grade', 'productivity_score'],
      dtype='str')

Soriting the columns I need

In [6]:
columns_needed = [
    "study_hours_per_day",
    "sleep_hours",
    "exercise_minutes",
    "stress_level",
    "final_grade"
]

In [7]:
needed_data = cleanedData[columns_needed]
needed_data.describe()

,study_hours_per_day,sleep_hours,exercise_minutes,stress_level,final_grade
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,5.254562,6.517799,59.648050,5.478750,70.266409
std,2.742876,2.029784,34.611751,2.866943,17.282277
min,0.500000,3.000000,0.000000,1.000000,40.000000
25%,2.900000,4.770000,30.000000,3.000000,55.460000
50%,5.250000,6.510000,60.000000,5.000000,70.315000
75%,7.640000,8.310000,90.000000,8.000000,85.340000
max,10.000000,10.000000,119.000000,10.000000,99.990000

Making sure there are no missing values

In [9]:
needed_data.isnull().sum()

study_hours_per_day    0
sleep_hours            0
exercise_minutes       0
stress_level           0
final_grade            0
dtype: int64